nsq:
  address: 172.31.207.179
  port: 4161
meili_search:
  address: search.yimi.tv
  port: 443
  api_key: YimiTVSearchMasterKey001!@
mysql:
  host: rm-j6cr0d71hb8289h68.mysql.rds.aliyuncs.com
  port: 3306
  account: duck_box
  password: duck_box@simonks1012@YimiTV
  db: yimitv
redis:
  host: r-j6ctv746qll7n47gfn.redis.rds.aliyuncs.com
  port: 6379
  account: duck_box
  password: duck_box@redis0726@YimiTV@
